name: "nightly-release"

on:
  push:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    TITLES_ARTIFACT: titles
    TITLES_ARTIFACT_PATH: titles.txt
    TITLES_ARCHIVE_ARTIFACT: titles-archive
    PREVIEWS_ARTIFACT: previews
    PREVIEWS_ARTIFACT_PATH: previews.txt
    PREVIEWS_ARCHIVE_ARTIFACT: previews-archive

jobs:
  build_titles:
    name: Build Titles
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_titles_archive
        run: |
          archive_file="${{ env.TITLES_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip -r "${archive_file}" titles

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_titles_archive.outputs.archive_file }}' > $TITLES_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TITLES_ARTIFACT }}
          path: ${{ env.TITLES_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TITLES_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_titles_archive.outputs.archive_file }}
          retention-days: 1

  build_previews:
    name: Build Previews
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_previews_archive
        run: |
          archive_file="${{ env.PREVIEWS_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip -r "${archive_file}" previews

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_previews_archive.outputs.archive_file }}' > $PREVIEWS_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREVIEWS_ARTIFACT }}
          path: ${{ env.PREVIEWS_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PREVIEWS_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_previews_archive.outputs.archive_file }}
          retention-days: 1

  release:
    needs: [ build_titles, build_previews ]
    name: Release
    runs-on: ubuntu-latest
    steps:
      # We'll need the repo if we want to use gh command line later
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # titles
      - name: Download Artifact (titles)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TITLES_ARTIFACT }}

      - name: Extract Archive Path (titles) and Store in Step Outputs
        id: store_titles
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $TITLES_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (titles)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TITLES_ARCHIVE_ARTIFACT }}

      # previews
      - name: Download Artifact (previews)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PREVIEWS_ARTIFACT }}

      - name: Extract Archive Path (previews) and Store in Step Outputs
        id: store_previews
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $PREVIEWS_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (previews)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PREVIEWS_ARCHIVE_ARTIFACT }}

      # Create new nightly
      - name: Release new nightly
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "latest" > /dev/null 2>&1; then
            gh release delete "latest" --cleanup-tag --yes
          fi
          gh release create "latest" --title "nightly release" --latest --target "${{ github.sha }}" \
            ${{ steps.store_titles.outputs.archive_path }} \
            ${{ steps.store_previews.outputs.archive_path }}
